spring:
   application:
      name: SmartRecibos
   datasource:
      url: jdbc:postgresql://localhost:5433/smart_recibos
      username: postgres
      password: postgres
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true
